## Tensor

In [1]:
import torch
import numpy as np

In [2]:
# Create Tensor directly from data - Data type will be predicted automatically
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)     # Convert ndarray into torch.Tensor

In [3]:
# Create Tensor from NumPy array - Also possible in vice versa
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
# Create Tensor from other tensor - Keep shape and datatype of input tensor until overriden
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)     # Overrides datatype of input tensor
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7969, 0.1505],
        [0.3628, 0.4550]]) 



In [7]:
shape = (2, 3,)

# Create Tensor with random / consistent values and shape
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeors Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.4922, 0.6330, 0.9713],
        [0.8898, 0.3247, 0.0653]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeors Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



### Attribute of Tensor

In [8]:
# The attribute of Tensor presents the shape, datatype and soring location of Tensor
tensor = torch.rand(3, 4)

print(f"Shape of Tensor: {tensor.shape}")
print(f"Datatype of Tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of Tensor: torch.Size([3, 4])
Datatype of Tensor: torch.float32
Device tensor is stored on: cpu


### Operation of Tensor

In [10]:
# If GPU is available, move Tensor to it.
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [13]:
# Indexing and Slicing of Tensor
tensor = torch.ones(4, 4)

print(f"First Row: {tensor[0]}")
print(f"First Column: {tensor[:, 0]}")
print(f"Last Column: {tensor[..., -1]}")

# Change values in the second column to 0
tensor[:, 1] = 0

print(tensor)

First Row: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1., 1.])
Last Column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [14]:
# Concatenate three of tensors into new tensor
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### Arithmetic Operations of Tensor

In [17]:
# Calculate matrix multiplication between 2 Tensors - y1, y2, y3 have same values
y1 = tensor @ tensor.T      # tensor.T means transpose of tensor
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# Calculate element-wise product - z1, z2, z3 have same values
z1 = tensor * tensor      # tensor.T means transpose of tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [18]:
# Single Element Tensor
# If the tensor is an aggregation of all values in a tensor, resulting in only 1 value, it can be converted into Python numeric value
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [20]:
# In-place Operation - Store the result of operation into operand. It has _ as suffix
print(f"{tensor} \n")

tensor.add_(5)      # Add 5 to the all values in tensor and store the result
print(f"{tensor} \n")

'''
 Note:
 In-place Operation can save some of memories.
 But it could make a problem in derivative operations because it instantly deletes the history.
'''

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



In [21]:
# Convert Tensor into NumPy array
t = torch.ones(5)
n = t.numpy()

print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


##### Note: If you change one of them, the other one will also be changed. It's because Tensor and NumPy array share the same memory in CPU.

In [22]:
# Changes in the Tensor are applied in the NumPy array
t.add_(1)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [24]:
# Convert NumPy array into Tensor
n = np.ones(5)
t = torch.from_numpy(n)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


In [25]:
# Changes in the NumPy array are applied in the Tensor
np.add(n, 1, out=n)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
